import { Inter } from "next/font/google";
import "./globals.css";
import TopNav from "./_components/topnav";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex flex-col min-h-screen`}>
        <header className="sticky top-0 z-50 bg-white shadow-md">
          <TopNav />
        </header>
        <main className="flex-grow">{children}</main>
      </body>
    </html>
  );
}
